stages:
  - build
  - deploy

make:
  stage: build
  script:
    - ./build.sh
  artifacts:
    paths:
      - cmake-build-debug/src/loadBalancer
      - cmake-build-debug/src/raft
      - cmake-build-debug/src/client
    expire_in: 1 hrs


checkName:
  stage: build
  script: 
    - bash -c '[ -s groupMembers.txt ]'

checkReport:
  stage: deploy
  script:
    - bash -c '[ -f report.pdf ]'
