stages:
  - build
  - test
  - deploy

make:
  stage: build
  script:
    - chmod +x build.sh
    - ./build.sh
  artifacts:
    paths:
      - cmake-build-debug/src/loadBalancer
      - cmake-build-debug/src/raft
      - cmake-build-debug/src/client
    expire_in: 1 hrs

checkName:
  stage: build
  script:
    - bash -c '[ -s groupMembers.txt ]'

runCorrectness:
  stage: test
  script:
    - RESULT=$(timeout 120 ./testCorrectness.sh)
    - RESULT=`echo "${RESULT}" | head -1`
    - EXPECTED='correct'
    - bash -c "[ "$RESULT" = "$EXPECTED" ]"

checkReport:
  stage: deploy
  script:
    - bash -c '[ -f report.pdf ]'
